In [3]:
# Create a NumPy array of shape (3,3) filled with zeros.
import numpy as np
arr = np.zeros((3,3))
print(arr)

arr = np.ones((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
# Create an array of number range [1..10]
arr = np.arange(1, 11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
# Create an array of 10 evenly spaced numbers between 5 and 50.
arr = np.linspace(5, 50, 10)
print(arr)


[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [36]:
# Generate a large population of random values (true population)
population = np.random.normal(loc=50, scale=15, size=10000)  # Mean=50, Standard Deviation=15
print(f'population shape = {population.shape} mean={population.mean()} std={population.std(ddof=0)}')

population shape = (10000,) mean=50.27587279146797 std=15.013289410158956


In [8]:
# Reshape a 1D array of size 9 into a 3x3 matrix.
arr = np.arange(9).reshape(3, 3)
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# Flatten a 2D array into a 1D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.flatten())


[1 2 3 4 5 6]


In [13]:
# Find the mean and standard deviation of an array.
arr = np.array([1, 2, 3, 4, 5])
print(f'{np.mean(arr)=}', f'{np.std(arr)=}')

np.mean(arr)=np.float64(3.0) np.std(arr)=np.float64(1.4142135623730951)


In [14]:
# Find the maximum and minimum values in an array.
arr = np.random.randint(1, 100, size=10)
print(f'{arr.max()=}', f'{arr.min()=}')


arr.max()=np.int64(98) arr.min()=np.int64(1)


In [15]:
# Multiply two matrices.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))


[[19 22]
 [43 50]]


In [17]:
# Extract all even numbers from a NumPy array.
arr = np.arange(1, 20)
print(arr[arr % 2 == 0])


[ 2  4  6  8 10 12 14 16 18]


In [18]:
# Replace all odd numbers in an array with -1.
arr = np.arange(1, 10)
arr[arr % 2 == 1] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [19]:
# Find indices of elements greater than a threshold.
arr = np.array([10, 20, 5, 30, 15])
print(np.where(arr > 15))


(array([1, 3]),)


In [20]:
# Create a 5x5 identity matrix.
print(np.eye(5))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
# Generate a random 4x4 matrix and normalize it.
A = np.random.rand(4, 4)
A = (A - A.min()) / (A.max() - A.min())
print(A)


[[0.         0.87664603 0.33633957 1.        ]
 [0.98364363 0.05782203 0.43046973 0.74387258]
 [0.54551603 0.73878483 0.87480079 0.24855668]
 [0.14429919 0.07552128 0.3307542  0.43017675]]


In [24]:
# Compute the row-wise sum of a 3x3 matrix.
A = np.random.randint(1, 10, (3, 3))
print(A)
print(A.sum(axis=1))


[[9 4 4]
 [1 2 1]
 [6 4 6]]
[17  4 16]


In [27]:
# Compute the column-wise sum of a 3x3 matrix.
A = np.random.randint(1, 10, (3, 3))
print(A)
print(A.sum(axis=0))


[[9 4 3]
 [2 3 6]
 [9 5 7]]
[20 12 16]


In [29]:
# Compute the moving average of a 1D array.
def moving_average(arr: np.ndarray, n=3):
    return np.convolve(arr, np.ones(n)/n, mode='valid')

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(moving_average(arr, 3))


[2. 3. 4. 5. 6. 7.]


In [30]:
# Find the dot product between two vectors.
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(np.dot(A, B))


32


In [31]:
# Implement a softmax function using NumPy.
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / exp_x.sum()

arr = np.array([1, 2, 3, 4])
print(softmax(arr))


[0.0320586  0.08714432 0.23688282 0.64391426]


In [33]:
# Implement a standard deviation function

import numpy as np

def standard_deviation(arr: np.ndarray, ddof: int = 0) -> float:
    """
    Compute the standard deviation of a NumPy array.

    Parameters:
    arr (np.ndarray): Input array.
    ddof (int): Delta Degrees of Freedom (0 for population, 1 for sample std).

    Returns:
    float: Standard deviation of the array.
    """
    mean = np.mean(arr)  # Compute mean
    variance = np.sum((arr - mean) ** 2) / (arr.size - ddof)  # Compute variance
    return np.sqrt(variance)  # Return standard deviation

# Example usage
arr = np.array([1, 2, 3, 4, 5])
print('Standard Deviation:', standard_deviation(arr))  # Output: 1.414
print('Sample Standard Deviation:', standard_deviation(arr, ddof=1))  # Output: 1.58



Standard Deviation: 1.4142135623730951
Sample Standard Deviation: 1.5811388300841898


In [32]:
# Find unique elements and their counts in an array.
arr = np.array([1, 2, 3, 2, 1, 4, 5, 5, 6])
unique, counts = np.unique(arr, return_counts=True)
print(dict(zip(unique, counts)))


{np.int64(1): np.int64(2), np.int64(2): np.int64(2), np.int64(3): np.int64(1), np.int64(4): np.int64(1), np.int64(5): np.int64(2), np.int64(6): np.int64(1)}
